apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mongo-test
  name: mongo-test-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: mongo-test
  type: ClusterIP
status:
  loadBalancer: {}
