apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: mongo-test
  name: mongo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mongo-test
  template:
    metadata:
      labels:
        run: mongo-test
    spec:
      containers:
      - image: mongo:3.4.9
        name: mongo-test
        envFrom:
        - secretRef:
            name: mongo-db-secret
        volumeMounts:
        - mountPath: /data/db
          name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-pv-volume-claim
#        - name: data
#          hostPath:
#            path: /mongodata
#            type: DirectoryOrCreate

