apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: node-api
  name: node-api-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: node-api
  type: ClusterIP
status:
  loadBalancer: {}
